<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="RecurringEventViewModel.cs" />
    <Compile Remove="SpecialEventViewModel.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Attendance.Data\Attendance.Data.csproj" />
  </ItemGroup>

</Project>
