<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Templates\Html\RRGC_Access_Code.html" />
    <None Remove="Templates\Text\RRGC_Access_Code.txt" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Templates\Html\RRGC_Access_Code.html" />
    <EmbeddedResource Include="Templates\Text\RRGC_Access_Code.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CSVFile" Version="3.2.1" />
    <PackageReference Include="Ical.Net" Version="5.1.2" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Attendance.Data\Attendance.Data.csproj" />
  </ItemGroup>

</Project>
